// app/fetchWithAuth/Base.tsx — DEPRECATED: importar desde "@/lib/http/endpoints"

export {
  URL_BASE,
  URL_BASE_QA,
  URL_BASE_CATALOGO,
  URL_BASE_26_5005,
  URL_BASE_168_5008,
  URL_BASE_92_5005,
  BASE_INVENTORY,
  URL_INVENTORY,
  URL_INVENTORY_STOCK,
  BASE_ORDERS,
  BASE_OMS,
  BASE_CUSTOMERS,
  BASE_WAREHOUSES,
  BASE_CATALOG,
  BASE_ID_SERVICE,
  BASE_ANALYSIS_SERVICE,
  BASE_ANALYSIS_SERVICE_CATALOGO,
  BASE_ANALYSIS_SERVICE_ANALYTICS,
  URL_BACKOMS,
} from "@/lib/http/endpoints";
